# Official documentation at http://goreleaser.com
project_name: githooks
builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: githooks
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    tags:
      containers_image_openpgp
    ldflags:
      - -X github.com/stefan-niemeyer/githooks/provenance.version={{.Version}}
      - -X github.com/stefan-niemeyer/githooks/provenance.gitCommit={{.ShortCommit}}
      - -X github.com/stefan-niemeyer/githooks/provenance.buildDate={{.Date}}
      - -w
      - -s
dist: bin
archives:
  - name_template: "githooks-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      linux: linux
      amd64: amd64
      arm64: arm64
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next-{{.ShortCommit}}"
changelog:
  skip: false
  sort: asc

nfpms:
  - file_name_template: "githooks-v{{ .Version }}-{{.Os}}-{{.Arch}}"
    homepage: https://github.com/stefan-niemeyer/githooks
    description: "githooks is a cli-tool to prevent commits without a Jira issue key in the first line of a commit message."
    maintainer: stefan-niemeyer
    license: None
    vendor: None
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      arm64: arm64
      linux: linux
