# Official documentation at http://goreleaser.com
version: 2

project_name: githooks

builds:
  - id: githooks-builds
    binary: githooks
    ldflags:
      - -X github.com/stefan-niemeyer/githooks/buildInfo.version={{.Version}}
      - -X github.com/stefan-niemeyer/githooks/buildInfo.gitCommit={{.ShortCommit}}
      - -X github.com/stefan-niemeyer/githooks/buildInfo.buildDate={{.Date}}
      - -w
      - -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: githooks-archives
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - UNLICENSE

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-next-{{.ShortCommit}}"

changelog:
  sort: asc

release:
  github:
    owner: stefan-niemeyer
    name: githooks
  prerelease: auto
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
