name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v .

      - name: Build OS ${{ matrix.os }} Arch ${{ matrix.arch }}
        run: mkdir -p ./bin && GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/githooks_${{ matrix.os }}_${{ matrix.arch }}

      - name: Bin
        uses: actions/upload-artifact@v2
        with:
          name: githooks_${{ matrix.os }}_${{ matrix.arch }}
          path: ./bin/githooks_${{ matrix.os }}_${{ matrix.arch }}